---
title: "db_build"
format: html
editor: source
---

## load packages

```{r}
#| output: false
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(tidyverse, RPostgres, DBI, here)

```

```{r}
#| output: false
tryCatch({
    drv <- dbDriver("Postgres")
    print("Connecting to Database…")
    connection <- dbConnect(drv,
                 dbname = Sys.getenv("aws_dbname"),
                 host = Sys.getenv("aws_host"),
                 port = Sys.getenv("aws_port"),
                 user = Sys.getenv("aws_user"),
                 password = Sys.getenv("aws_password"),
                 timezone=NULL)
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })

# set schema path
dbExecute(connection, "set search_path to 'bay_area'")
```

## build

```{r}

# location
dbExecute(connection, "alter table site add primary key(site_id);")

# wetland info
dbExecute(connection, "alter table wetland_info add primary key(survey_id);")

dbExecute(connection,
          "alter table wetland_info  
           add constraint fk_wetland foreign key (site_id) 
          references site (site_id);")

# water info - still needs work
dbExecute(connection, "alter table water_quality_info add primary key(water_id);")

dbExecute(connection,
          "alter table wetland_info  
           add constraint fk_water foreign key (water_id) 
          references  water_quality_info (water_id);")

# amphib dissect
dbExecute(connection, "alter table amphib_dissect add primary key(dissect_id);")

dbExecute(connection,
          "alter table amphib_dissect  
           add constraint fk_amphib_dissect foreign key (survey_id) 
          references wetland_info (survey_id);")

# amphib parasite
dbExecute(connection, "alter table amphib_parasite add primary key(parasite_id);")

dbExecute(connection,
          "alter table amphib_parasite  
           add constraint fk_amphib_parasite foreign key (dissect_id) 
          references amphib_dissect (dissect_id);")

# Bd - Not working
dbExecute(connection, "alter table bd_results add primary key(bd_id);")

dbExecute(connection,
          "alter table amphib_dissect  
           add constraint fk_bd foreign key (bd_id) 
          references bd_results (bd_id);")


# net_info
dbExecute(connection, "alter table net_info add primary key(seine_id);")

dbExecute(connection,
          "alter table net_info
          add constraint fk_net_info foreign key (site_id)
          references site (site_id)")

dbExecute(connection, # not working
          "alter table net_info 
          add constraint fk_wet_net_info foreign key (survey_id)
          references wetland_info (survey_id);")

# net species_info
dbExecute(connection, "alter table net_species add primary key(net_species_id);")

dbExecute(connection,
          "alter table net_species
          add constraint fk_net_species foreign key (seine_id)
          references net_info (seine_id);")

```
